DotrA/Controllers/MemberController.cs
using DotrA.Filters;
using DotrA.Models;
using DotrA.Service.Security.Web;
using DotrA_Lab.Business.DomainClasses;
using DotrA_Lab.InternalDataService;
using DotrA_Lab.InternalDataService.Implementation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DotrA.Controllers
{
    public class MemberController : BaseController
    {
        public MemberController(IAllService all) : base(all) { }

        #region ===註冊 Register===
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(MemberRegisterViewModel source)
        {
            string message = "";
            if (ModelState.IsValid)
            {
                #region //檢查信箱是否已經存在
                if (All.MS().CheckNullable(x => x.Email == source.Email))
                {
                    ModelState.AddModelError("EmailExist", "Email已經存在請更換!! This Email already exist");
                    return View();
                }
                #endregion
                #region //檢查帳號是否已經存在
                if (All.MS().CheckNullable(x => x.MemberAccount.Equals(source.MemberAccount)))
                {
                    ModelState.AddModelError("AccountExist", "此帳號已經存在，請更換帳號!! This Account already registered.");
                    //ViewBag.Message = "此帳號已經存在，請更換帳號!!";
                    return View();
                }
                #endregion

                string ActivationCode = All.MS().AddMember(source, source.Password);

                #region //寄送帳號啟用信 Send Email to Account
                SendVerifyOrResetEmail(source.Email, ActivationCode);
                message = "註冊成功，驗證帳號連結已寄到您的信箱. Registration successfully done. Account activation link " +
                    " has been sent to your Email : " + source.Email; /*"恭喜!!  " + member.MemberAccount + "  已成功註冊"*/
                #endregion

                ModelState.Clear();//清除 (包含錯誤訊息與模型繫結的資料都會被清空)
                ViewBag.Message = message;
                //return RedirectToAction("Login");
            }
            return View();
        }
        #region ===寄送驗證Email/重設密碼Email SendVerificationLinkEmailorSendResetPasswordLinkEmail===
        [NonAction]
        public void SendVerifyOrResetEmail(string Email, string activationCode, string emailFor = "VerifyAccount")
        {
            var verifyUrl = "/Member/" + emailFor + "/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress("minishopbs@gmail.com", "MiniShop");
            var toEmail = new MailAddress(Email);
            var fromEmailPassword = "edaybsazwbmogabr"; // Replace with actual password

            string subject = "";
            string body = "";
            if (emailFor == "VerifyAccount")
            {
                subject = "您的會員帳號已成功建立! Your account is successfully created!";
                body = "親愛的會員您好，很高興告訴您，您的MiniShop帳號已成功建立，請點擊下方連結進行帳號驗證.<br/><br/>" +
                    "Hi,<br/><br/>We are excited to tell you that your MiniShop account is" +
                    " successfully created. Please click on the below link to verify your account" +
                    " <br/><br/><a href=" + link + ">請點此驗證帳號. Account activation link</a> ";

            }
            else if (emailFor == "ResetPassword")
            {
                subject = "重設密碼! Reset Password!";
                body = "親愛的會員您好,我們收到您重設密碼的請求，請點擊下方連結重設密碼.<br/><br/>" +
                    "Hi,<br/><br/>We got request for reset your account password. Please click on the below link to reset your password" +
                    "<br/><br/><a href=" + link + ">請點此重設密碼. Reset Password link</a>";
            }


            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }
        #endregion
        #endregion
        #region ===驗證帳號 VerifyAccount===
        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {
            bool Status = false;
            if (Guid.TryParse(id, out Guid go))
            {
                if (All.MS().CheckNullable(x => x.ActivationCode == go))
                {
                    var Account = All.MS().GetFirst(x => x.ActivationCode == go);
                    All.MS().VerifyAccount(Account);
                    var role = All.MRS().GetUserRole(Account.RoleID);

                    AuthenticationHelper.CreateAuthCookie(Account.MemberID, Account.Name, Account.Email, Account.Password, role.RoleName);
                    Status = true;
                }
                else
                    ViewBag.Message = "無效的操作。Invalid Request.";
            }
            else
                ViewBag.Message = "無效的操作。Invalid Request.";

            ViewBag.Status = Status;
            return View();
        }
        #endregion
        #region ===登入Login/登出Logout===
        // GET: Members/Login
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel source)
        {
            if (All.MS().CheckNullable(x => x.MemberAccount == source.MemberAccount && x.Password != null))
            {
                if (!All.MS().CheckEmailVerify(source.MemberAccount))
                {
                    TempData["Message"] = "請先到信箱啟動驗證. Please verify your email first.";
                    return Redirect(Request.UrlReferrer.ToString());
                }

                var Account = All.MS().UserLogin(source.MemberAccount, source.Password);

                if (Account != null)
                {
                    #region ===驗證票證===
                    var role = All.MRS().GetUserRole(Account.RoleID);

                    AuthenticationHelper.CreateAuthCookie(Account.MemberID, Account.Name, Account.Email, Account.Password, role.RoleName, source.RememberMe);
                    #endregion
                    return RedirectToAction<HomeController>(x => x.Index());
                }
                TempData["Message"] = "帳號或密碼輸入錯誤!! Invallid Account or Password.";
                return Redirect(Request.UrlReferrer.ToString());
            }
            TempData["Message"] = "帳號或密碼輸入錯誤!! Invallid Account or Password.";
            return Redirect(Request.UrlReferrer.ToString());
        }


        [SecuredOperationFilter(Roles = "admin")]
        public ActionResult LoggedIn()
        {
            if (User.Identity.IsAuthenticated)
                return View();
            else
                return RedirectToAction("Login");
        }

        public ActionResult Logout()
        {
            AuthenticationHelper.Logout();
            return RedirectToAction("Index", "Home");
        }
        #endregion
        #region ===修改會員資料===
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var member = All.MS().GetSpecificDetailToViewModel<MemberModifyViewModel>(x => x.MemberID == id, x => x.MemberRole);

            if (member == null)
                return HttpNotFound();

            return View(member);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MemberModifyViewModel source)
        {
            if (ModelState.IsValid)
            {
                var user = All.MS().GetFirst(x => x.MemberID == ((DotrA.Service.Security.Identity)User.Identity).Id);
                var hashpassword = Hash.EncodePassword(source.Password, user.HashCode);
                if (All.MS().CheckNullable(x => x.MemberAccount == source.MemberAccount && x.Password == hashpassword))
                {
                    if (source.RePassword == null)
                    {
                        source.Password = hashpassword;
                        All.MS().UpdateViewModelToDatabase(source, x => x.MemberID == ((DotrA.Service.Security.Identity)User.Identity).Id);
                    }
                    else
                        All.MS().MemberMoidfyPassword(source, ((DotrA.Service.Security.Identity)User.Identity).Id, source.RePassword);
                    return RedirectToAction<HomeController>(x => x.Index());
                }
                ModelState.AddModelError("Password", "原始密碼錯誤");
            }
            return View(source);
        }
        #endregion
    }
}

DotrA/Controllers/OrderController.cs
using DotrA_Lab.InternalDataService.Implementation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotrA.Controllers
{
    public class OrderController : BaseController
    {
        public OrderController(IAllService all) : base(all) { }

        // GET: Order
        public ActionResult Index()
        {
            return View();
        }
    }
}

DotrA/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotrA.Models;
using DotrA_Lab.InternalDataService.Implementation;
using PagedList;

namespace DotrA.Controllers
{
    [Authorize]
    public class ShopController : BaseController
    {
        public ShopController(IAllService all) : base(all) { }

        // GET: Shop
        public ActionResult Index(int? pid, int page = 1)
        {
            bool IsInt_pid = int.TryParse(pid.ToString(), out int id);

            var result = All.PS().GetListToViewModel<ProductView>(x => x.Status == true && (!IsInt_pid || x.ProductID == id));

            ViewBag.MyPageList = result.ToPagedList(page, 9);

            return View();
        }

        [ChildActionOnly]
        public ActionResult ProductList()
        {
            return PartialView(All.CS().GetListToViewModel<ProductListView>());
        }
    }
}

DotrA/Controllers/ShoppingCartController.cs
using DotrA.Models.Cart;
using System.Web.Mvc;

namespace DotrA.Controllers
{
    public class ShoppingCartController : Controller
    {
        //取得目前購物車頁面
        public ActionResult GetCart()
        {
            return PartialView("_CartPartial");
        }

        //以id加入Product至購物車，並回傳購物車頁面
        public ActionResult AddToCart(int id)
        {
            var currentCart = Operation.GetCurrentCart();
            currentCart.AddProduct(id);
            return PartialView("_CartPartial");
        }
        //以id刪除Product至購物車，並回傳購物車頁面
        public ActionResult RemoveFromCart(int id)
        {
            var currentCart = Operation.GetCurrentCart();
            currentCart.RemoveProduct(id);
            return PartialView("_CartPartial");
        }
        //以id刪除全部Product至購物車，並回傳購物車頁面
        public ActionResult ClearCart()
        {
            var currentCart = Operation.GetCurrentCart();
            currentCart.ClearCart();
            return PartialView("_CartPartial");
        }
    }
}

DotrA/Views/Shared/_Footer-Gallery.cshtml
<section class="ftco-gallery">
    <div class="container-fluid px-0">
        <div class="row no-gutters">
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="../../Assets/images/gallery-7.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(../../Assets/images/footer/gallery-1.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="../../Assets/images/gallery-8.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(../../Assets/images/footer/gallery-2.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="../../Assets/images/gallery-9.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(../../Assets/images/footer/gallery-3.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="../../Assets/images/gallery-10.png" class="gallery image-popup img d-flex align-items-center" style="background-image: url(../../Assets/images/footer/gallery-4.png);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="../../Assets/images/gallery-11.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(../../Assets/images/footer/gallery-5.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="../../Assets/images/gallery-12.png" class="gallery image-popup img d-flex align-items-center" style="background-image: url(../../Assets/images/footer/gallery-6.png);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

DotrA/Views/Shared/_Header.cshtml
<div class="py-1 bg-black">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center">
                            <span class="icon-phone2"></span>
                        </div>
                        <span class="text">0922-932-002</span>
                    </div>
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center">
                            <span class="icon-paper-plane"></span>
                        </div>
                        <span class="text">minishopbs@gmail.com</span>
                    </div>
                    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                        <span class="text">3-5 Business days delivery &amp; Free Returns</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DotrA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>

    <style type="text/css">
        .text-center, body, .hero-wrap {
            font-family: 'Microsoft JhengHei' !important;
            font-weight: 900;
        }

        @@media (min-width: 990px) {
            .home-tag {
                position: relative;
            }

                .home-tag > :before {
                    content: '';
                    width: 1px;
                    bottom: 17px;
                    position: absolute;
                    right: 60px;
                    transition: 0.7s all;
                }

                .home-tag > :hover:before {
                    border-bottom: 2px solid #313131;
                    right: 15px;
                    width: 50px;
                }
        }

        .imgtag img {
            width: 200px;
            height: 50px;
        }
    </style>
    @Styles.Render("/home/css")
    @RenderSection("topCSS", required: false)
</head>
<body class="goto-here">
    @Html.Partial("_Header")
    @Html.Partial("_navbar")
    <!-- END nav -->

    @RenderBody()

    @Html.Partial("_Footer-Gallery")
    @Html.Partial("_footer")
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" />
        </svg>
    </div>


    @*@Scripts.Render("/minishop/js")*@

    <script src="@Url.Content("/Assets/minishop/js/jquery.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/jquery-migrate-3.0.1.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/popper.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/jquery.easing.1.3.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/jquery.waypoints.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/jquery.stellar.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/owl.carousel.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/jquery.magnific-popup.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/aos.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/jquery.animateNumber.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/bootstrap-datepicker.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/scrollax.min.js")"></script>
    <script src="@Url.Content("/Assets/minishop/js/main.js")"></script>

    @RenderSection("endScripts", required: false)
    @RenderSection("Scripts", required: false)
    @if (TempData["Message"] != null)
    {
        <script type="text/javascript">
            $(function () {
                $('#LoginModal').modal('show');
            });
        </script>
    }
    <script type="text/javascript">
        //加入編號為productId的商品進購物車
        function AddToCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddToCart", "ShoppingCart")',
                data: { id: productId }
            })
            .done(function (msg) {
                //將回傳的購物車頁面 填入 li#Cart
                $('li#Cart').html(msg);
            });
        }
        function RemoveFromCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("RemoveFromCart", "ShoppingCart")',
                data: { id: productId }
            })
            .done(function (msg) {
                //將回傳的購物車頁面 填入 li#Cart
                $('li#Cart').html(msg);
            });
        }
        function ClearCart() {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ClearCart", "ShoppingCart")',
                data: {  }
            })
            .done(function (msg) {
                //將回傳的購物車頁面 填入 li#Cart
                $('li#Cart').html(msg);
            });
        }
    </script>
</body>
</html>

DotrA/Views/Shared/_LoginModal.cshtml
@model LoginViewModel


<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">會員登入</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">

            <div class="container">
                <h7 class="text-danger"><i>@TempData["Message"]</i></h7>
                @using (Html.BeginForm("Login", "Member"))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal text-center">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group ">
                            @Html.LabelFor(model => model.MemberAccount, htmlAttributes: new { @class = "control-label " })
                            <div class="">
                                @Html.EditorFor(model => model.MemberAccount, new { htmlAttributes = new { @class = "form-control ", @placeholder = "請輸入帳號" } })
                                @Html.ValidationMessageFor(model => model.MemberAccount, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label " })
                            <div class="">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "請輸入密碼" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.RememberMe, htmlAttributes: new { @class = "control-label " })
                            <div class="">
                                <div class="">
                                    @Html.EditorFor(model => model.RememberMe)
                                    @Html.ValidationMessageFor(model => model.RememberMe, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Login" class="btn" />
                        </div>
                        <div class="row justify-content-between">
                            <div class="col-6"><a class="btn" href="@Url.Action("ForgotPassword", "Member")" role="button">Forgot Password</a></div>
                            <div class="col-6"><a class="btn" href="@Url.Action("Register", "Member")" role="button">Click To Register</a></div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

DotrA/Views/Shared/_Topimage.cshtml
<div class="hero-wrap hero-bread" style="background-image: url('../../Assets/images/header/bg_6.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Shop</span></p>
                <h1 class="mb-0 bread">Shop</h1>
            </div>
        </div>
    </div>
</div>

DotrA/Views/Shared/_cartpartial.cshtml
@{
    //取得當前購物車所有內容
    var currentCart = DotrA.Models.Cart.Operation.GetCurrentCart();
}

<a id="CartDropDown" class="dropdown-toggle nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="icon-shopping_cart">購物車</span>
</a>
<div class="dropdown-menu" role="menu" aria-labelledby="CartDropDown" style="width:auto">
    @if (currentCart.Count > 0)
    {
        foreach (var cartitem in currentCart)
        {
            <div>
                <a class="dropdown-item">
                    <div class="col-3">@cartitem.ProductName  @cartitem.Quantity 個 <span onclick="RemoveFromCart('@cartitem.ProductId')">&times;</span></div>
                </a>
            </div>

        }
        <div class="container">
            <a class="dropdown-item">
                <div class="row">
                    <div class="col-6">
                        <botton onclick="location.href='@Url.Action("Index","Order")'"><span>結帳去</span></botton>
                    </div>
                    <div class="col-6">
                        <botton onclick="ClearCart()"><span>清空</span></botton>
                    </div>
                </div>
            </a>
        </div>
    }
    else
    {
        <a class="dropdown-item" href="#">購物車無任何商品</a>
    }
</div>

DotrA/Views/Shared/_footer.cshtml
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row">
            <div class="mouse">
                <a href="#" class="mouse-icon">
                    <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                </a>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Dotra</h2>
                    <p>一個提供多元豐富的商品銷售社群平台</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Menu</h2>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Index","Shop")" class="py-2 d-block">商品</a></li>
                        <li><a href="@Url.Action("About","Home")" class="py-2 d-block">關於我們</a></li>
                        @*<li><a href="#" class="py-2 d-block">Journal</a></li>
                            <li><a href="#" class="py-2 d-block">Contact Us</a></li>*@
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <div class="d-flex">
                        <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                            <li><a href="#" class="py-2 d-block">親子</a></li>
                            <li><a href="#" class="py-2 d-block">生活</a></li>
                            <li><a href="#" class="py-2 d-block">休閒食品</a></li>
                            <li><a href="#" class="py-2 d-block">3C配件</a></li>
                            @*<li><a href="#" class="py-2 d-block">授權商品</a></li>*@
                        </ul>
                        <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                            @*<li><a href="#" class="py-2 d-block">3C配件</a></li>*@
                            <li><a href="#" class="py-2 d-block">授權商品</a></li>
                        </ul>
                        @*<ul class="list-unstyled">
                                <li><a href="#" class="py-2 d-block">FAQs</a></li>
                                <li><a href="#" class="py-2 d-block">Contact</a></li>
                            </ul>*@
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Question?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li>
                                <span class="icon icon-map-marker"></span><span class="text">
                                    106 臺北市忠孝東路三段1號
                                </span>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="icon icon-phone"></span><span class="text">
                                        0922-932-002
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="icon icon-envelope"></span><span class="text">minishopbs@gmail.com</span>
                                </a>
                            </li>
                            <li>
                                <a href="https://lin.ee/8ymgbmK"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/zh-Hant.png" alt="加入好友" height="36" border="0"></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template
                    is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

DotrA/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a href='@Url.Action("Index", "Home")' class="imgtag">
            <img src='@Url.Content("~/Assets/images/Logo/logo.png")' />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item home-tag">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                <li class="nav-item home-tag">@Html.ActionLink("Shop", "Index", "Shop", new { id = Session["MemberID"] }, new { @class = "nav-link" })</li>
                <li class="nav-item home-tag">@Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })</li>
                @Helper.GetIdentity(this)
            </ul>
        </div>
    </div>
</nav>
@if (!User.Identity.IsAuthenticated)
{
    <!-- Modal -->
    <div class="modal" id="LoginModal" tabindex="-1" role="dialog">
        @{Html.RenderPartial("_LoginModal", new LoginViewModel());}
    </div>
}